#!/usr/bin/env python
# coding: utf-8
# Corpus and dictionary class for translation exercise

import pprint
import itertools as it
import re

class Dict:
	english_sentences = ["As an administrator, you can add user accounts, set up Mac OS X for multiple users, change certain system settings, and have greater access to the computer.", "Its color, depth, and motion guide you through your tasks, while the Finder and Dock provide easy access to your computer and network.", "Throughout this book, you’ll see questions like the one below.", "The number shows how many messages you have to read.", "Drag items in the toolbar to arrange them.", "You can easily set up your computer for several people by adding user accounts and requiring users to log in.", "For the most security, log in as a user who is not an administrator", "This red icon indicates that you are connected.", "Send short notices to colleagues or pictures of the kids to the folks.", "To see a picture in email you receive from this person, drag the picture here", "This printer is the default.", "If you can’t find this information, look in the applications you use to get email or browse the Web.", "You need to type this name and password exactly the same way if you set up Mac OS X for multiple users.", "When you log in as an administrator you have greater access to the computer, so you may not want to leave your computer unattended.", "Click here to see the system preferences."]
	spanish_sentences = ["Cuando se accede al ordenador como un administrador, pueden añadirse otros usuarios, configurar Usuarios Múltiples de Mac OS X, cambiar determinados ajustes del sistema y, en general, disponer de mayor acceso al sistema.", "Su color, profundidad, y movimiento ayudan a guiarlo con sus deberes, el Finder y el Dock permiten acceder al ordenador y conectarse a redes cómodamente.", "A lo largo del manual, observará preguntas como la que aparece a continuación.", " El número indica los mensajes pendientes de lectura.", "Para ordenar los ítems en la barra de herramientas, arrástrelos.", "Podrá configurarlo fácilmente añadiendo cuentas de usuario que requieran el uso de nombres de usuario y contraseñas.", "Para mayor seguridad, inicie la sesión con un usuario distinto al administrador", "Este icono rojo indica que está conectado.", "Envíe notas cortas a sus compañeros o mande fotografías de sus hijos a otras personas.", "Para visualizar una imagen incluida en un mensaje de esa persona, arrástrela hasta aquí.", "Ésta es la impresora por omisión.", "Si no encuentra la información, búsquela en la aplicación de correo o en el navegador web.", "Escriba el nombre y la contraseña exactamente igual que si configurase el Mac OS X para múltiples usuarios.", "Cuando se inicia la sesión como administrador se dispone de mayores privilegios de acceso, por lo que no conviene abandonar el ordenador.", "Haga clic aquí para visualizar las preferencias del sistema."]


	#build dictionary set
	f_set = set()
	for sentence in spanish_sentences:
		f_set = f_set.union(sentence.split())
	f_set = sorted(f_set)

	dictionary = {
		'a': ['to', 'at', 'of', 'into', 'by', 'per', 'upon'],
		'abandonar': ['drop out', 'leave', 'abandon', 'quit', 'relinquish', 'drop', 'throw off', 'ditch', 'chuck', 'forsake', 'desert', 'walk out on'],
		'accede': ['access', 'log in', 'log on'],
		'acceder': ['log in', 'log on'],
		'acceso': ['access', 'approach', 'entry', 'accession', 'fit', 'attack', 'spasm', 'outburst'],
		'administrador': ['administrator', 'manager'],
		'ajustes': ['settings', 'adjustment', 'fit', 'patch'],
		'al': ['to the', 'at the'],
		'aparece': ['appears', 'shows','shows up', 'turns up', 'comes into view', 'emerge', 'come out', 'come on the scene', 'loom up', 'loom', 'arrive', 'come up', 'walk', 'intervene', 'develop'],
		'aplicación': ['application', 'enforcement'],
		'aquí': ['here', 'hither'],
		'arrástrela': ['drag it'],
		'arrástrelos': ['drag them'],
		'ayudan': ['help', 'assist', 'aid', 'abet', 'pull up', 'advance', 'boost', 'dole', 'subserve', 'favor', 'help out', 'support', 'lend a hand', 'tide over', 'help along'],
		'añadirse': ['add', 'lend'],
		'añadiendo': ['adding'], #NEEDS MORE
		'barra': ['bar', 'rod', 'pole', 'stick'],
		'búsquela': ['search for it'],
		'cambiar': ['change', 'exchange', 'switch', 'swap', 'swop', 'alter', 'vary', 'swing', 'turn around', 'shift', 'transfer', 'dislocate', 'swap around', 'swap round', 'swap over', 'distort'],
		'clic': ['click', 'snap fastener'],
		'color': ['color', 'flush', 'hue', 'tint', 'dye', 'tail'],
		'como': ['as', 'like', 'by way of'],
		'cómodamente': ['comfortably', 'snugly', 'cosily', 'cose'],
		'compañeros': ['partners', 'mates', 'companions', 'associates', 'fellows', 'buddies', 'brothers', 'chums', 'sidekicks', 'compeers', 'schoolfellows', 'stooges', 'friends at court'],
		'con': ['with', 'by'],
		'conectado': ['connected', 'on-line'],
		'conectar': ['connect', 'plug in', 'plumb in', 'log in'],
		'configurar': ['configure', 'form'],
		'configurarlo': ['configure it'],
		'conectarse': ['connect'], #NEEDS MORE
		'continuación': ['continuation', 'sequel', 'continuance', 'carrying-on', 'resumption', 'ongoing', 'follow', 'prosecution'],
		'contraseña': ['password'],
		'contraseñas': ['passwords'],
		'conviene': ['should', 'agree', 'concur', 'suit', 'fall in', 'do', 'answer', 'arrange'],
		'correo': ['mail', 'post', 'message'],
		'cortas': ['short', 'curt', 'stumpy', 'scanty', 'skimpy', 'brief', 'bashful', 'timid', 'narrow'],
		'cuenta': ['account', 'bill', 'count', 'reckoning', 'tally', 'calculation', 'estimate', 'score', 'tab', 'check'],
		'cuentas': ['accounts', 'bills', 'counts', 'reckonings', 'tallys', 'calculations', 'estimates', 'scores', 'tabs', 'checks'],
		'cuando': ['when', 'as', 'whenever', 'if', 'at the time of', 'in the event of'],
		'de': ['of', 'from', 'by', 'about', 'at', 'with', 'out', 'off', 'than'],
		'deberes': ['homework', 'schoolwork'],
		'del': ['the', 'from the', 'of the'],
		'determinados': ['certain', 'determined', 'particular', 'specific', 'resolute', 'determinate', 'definite', 'appointed', 'purposeful', 'disposed'],
		'dispone': ['available', 'provides', 'disposes', 'arranges', 'orders', 'lays down', 'sets out', 'lays out', 'ordains', 'frames', 'prepares', 'readies', 'dictates', 'commands', 'forms up', 'lines up', 'trims'],
		'disponer': ['available', 'provide', 'dispose', 'arrange', 'order', 'lay down', 'set out', 'lay out', 'ordain', 'frame', 'prepare', 'ready', 'dictate', 'command', 'form up', 'line up', 'trim'],
		'distinto': ['different', 'dissimilar', 'distinct', 'separate', 'diverse', 'varied', 'several'],
		'dock': ['Dock'],
		'el': ['the'],
		'en': ['in', 'on', 'at', 'to', 'into', 'for', 'by', 'about'],
		'encuentra': ['found', 'finds', 'locates', 'espies', 'spots', 'meets', 'encounters', 'comes upon', 'traces', 'pitches upon'],
		'es': ['is'],
		'este': ['this'], #NEEDS MORE
		'esa': ['that'],
		'está': ['is'],
		'envíe': ['submits', 'sends', 'posts', 'ships', 'taps out', 'forwards', 'dispatches', 'despatches', 'remits', 'consigns', 'extends', 'sends away', 'packs off'],
		'escriba': ['scribe', 'write'],
		'exactamente': ['exactly', 'just', 'precisely', 'accurately', 'quite', 'strictly', 'punctually', 'correctly', 'right', 'truly'],
		'finder': ['Finder'],
		'fotografías': ['photographs', 'pictures', 'photographies', 'photos'],
		'fácilmente': ['easily', 'easy', 'readily', 'with ease'],
		'general': ['general', 'broad', 'extensive', 'blanket', 'sweeping', 'catch-all', 'omnibus'],
		'guiarlo': ['guide you', 'guide it'],
		'hasta': ['to', 'until', 'till', 'as far as', 'unto', 'through', 'pending', 'up', 'even', 'through'],
		'herramientas': ['tools', 'gear', 'outfit', 'kit'],
		'hijos': ['offspring', 'children'],
		'icono': ['icon', 'ikon'],
		'igual': ['equal', 'same', 'like', 'alike', 'even', 'duplicate', 'uniform', 'match', 'peer', 'fellow'],
		'imagen': ['image', 'picture', 'vizualization'],
		'impresora': ['printer'],
		'incluida': ['included'],
		'indica': ['indicates', 'suggests', 'shows', 'designates', 'tells', 'points to', 'points out', 'points at', 'signals', 'notes', 'signifies', 'denotes'],
		'información': ['information', 'data', 'enlightenment', 'dope', 'blow', 'item', 'intelligence'],
		'inicia': ['begins', 'starts', 'initiates', 'launches', 'logs in', 'logs on', 'comes on', 'opens', 'takes up', 'strikes up', 'leads off', 'pioneers', 'takes to', 'enters into'],
		'inicie': ['begins', 'starts', 'initiates', 'launches', 'logs in', 'logs on', 'comes on', 'opens', 'takes up', 'strikes up', 'leads off', 'pioneers', 'takes to', 'enters into'],
		'la': ['the', 'a', 'it'],
		'largo': ['long', 'lengthy'],
		'las': ['the', 'them'],
		'lectura': ['reading', 'lecture'],
		'haga': ['do', 'make', 'ask'],
		'mac': ['Mac'],
		'ésta': ['this'],
		'ítems': ['items'],
		'y': ['and'],
		'web': ['web'],
		'visualizar': ['visualize', 'see'],
		'usuarios': ['users', 'readers'],
		'usuario': ['user', 'reader'],
		'uso': ['use', 'purpose', 'using', 'usage', 'utilization', 'employment', 'fashion', 'wear'],
		'una': ['a'],
		'un': ['a'],
		'tal': ['such'],
		'sus': ['your', 'their', 'its', 'his', 'her'],
		'sistema': ['system', 'scheme', 'method', 'framework', 'machinery'],
		'si': ['if', 'whether', 'once', 'supposing'],
		'sesión': ['session', 'sitting', 'meeting', 'performance'],
		'seguridad': ['security', 'safety', 'safeness', 'reliability', 'sureness', 'assurance', 'assuredness', 'certain', 'certainty', 'certitude'],
		'se': ['NULL'],
		'requieran': ['require', 'want'],
		'redes': ['networks'],
		'rojo': ['red'],
		'que': ['that', 'what', 'than'],
		'pueden': ['can', 'are able to'],
		'profundidad': ['depth', 'profoundness', 'deepness', 'profundity'],
		'privilegios': ['privileges', 'concession', 'charter', 'right'],
		'preguntas': ['questions'],
		'preferencias': ['preferences', 'choices'],
		'podrá': ['one can'], #NEEDS MORE
		'por': ['by', 'for', 'per', 'to', 'through', 'because of', 'out of', 'as', 'via', 'at', 'after', 'around', 'about', 'along', 'out', 'down'],
		'personas': ['people'],
		'persona': ['person'],
		'permiten': ['allow', 'permit', 'let', 'enable', 'emend', 'allow in', 'allow out', 'admit of', 'give', 'empower'],
		'pendientes': ['pending', 'outstanding', 'unread'],
		'para': ['for', 'to', 'in order to', 'as', 'by', 'at', 'as for', 'of', 'so as to'],
		'otros': ['other', 'others'],
		'otras': ['other', 'others', 'another'],
		'ordenar': ['order', 'arrange', 'sort', 'classify', 'assort', 'demand','command','put in order', 'set in order','ordain', 'fill an order', 'tidy up', 'tidy out','confer' , 'line up'],
		'ordenador': ['computer', 'machine', 'laptop'],
		'omisión': ['omission', 'default','skip' ,'gap', 'cuff'],
		'observará': ['you will see', 'will see'],
		'o': ['or', 'either'],
		'número': ['number','issue' ,'turn', 'act' ,'figure' ,'numeral' , 'copy', 'size', 'circulation'],
		'notas': ['notes', 'grades', 'you notice', 'you will notice', 'you will see'],
		'nombres': ['names'], 
		'nombre': ['name', 'forename' ,'appelation', 'cognomen','noun'],
		'no': ['no', 'don\'t','not', 'nay'],
		'navegador': ['navigator', 'browser'],
		'múltiples': ['multiple'],
		'movimiento': ['movement', 'motion','move','shift','shake','wag','twitch','swing','wave','flourish','flutter','activity','action','bustle','lurch'],
		'mensajes': ['messages'],
		'mensaje': ['message','dispatch','despach'],
		'mayores': ['older', 'greater','higher'],
		'mayor': ['older', 'greater','higher','major','main','chief','senior','high','big','adult','elder','bigger'],
		'manual': ['manual', 'guide','handbook'],
		'mande': ['send', 'sends'],
		'los': ['the', 'those','them'],
		'lo': ['', 'it', 'the','him','to it'],	
		'múltiple': ['numerous', 'multiple','manifold','multifold','multifarious'],
		'ordenador': ['computer'],
		'os': ['OS'],
		'su': ['his'], #NEEDS MORE
		'otro': ['other', 'another','another one'],
		'poder': ['can', 'be able to','may','might'],
		'tal': ['such', 'that', 'just as'],
		'usuario': ['user', 'username','reader'],
		'Usuarios': ['users'],
		'x': ['X'],
	}